### ISSUE TITLE
Add more domains and fix bug

### ISSUE THREAD

**Issue by danielperez9430** [botfactoryit/flarum-amazon-affiliation#1]
Hello, First good job for this extension

**Sugguest:  Add amazon Es, Fr, ... and multi tag.**

Ej:  Afiliate id ES:  ?tag=XXXX-21
     Afiliate id FR: ?tag=XXXX-21

In my case I used amazon ES and Com. 

**Bug:**
This extensio don't work If I activate the extension Media embed (s9e/flarum-ext-mediaembed)
Link: https://github.com/s9e/flarum-ext-mediaembed

Thacks you for your good extension for Flarum 👍

**Comment by matteocontrini** [comment]
Hi Daniel, thanks for the feedback. I wasn't actually expecting someone to use this extention, but it's indeed ready for anyone to use :)

For your first request: it's easy to add support for amazon.es. Take a look at the source code, [line 35](https://github.com/botfactoryit/flarum-amazon-affiliation/blob/master/js/forum/src/main.js#L35). Feel free to send a pull request for that. Not sure what you mean with "multi tag" instead. Do you mean using a different tag for each "nation"?

For the bug report: it should work fine, I tested this extention specifically to work together with mediaembed. What issue are you experiencing specifically?

**Comment by danielperez9430** [comment]
Example:

The affiliate program in Amazon in different. You need to subscribe in more regions. 
For example if you subscribe in amazon es, the tag only used by Amazon es. No work in Amazon com

Examples:
Amazon.es use tag  xxxx-21
Amazon.com use tag xxxx-20

**Comment by danielperez9430** [comment]
The bug fixed I update the extension segure https.
The error Http 1.1 fixed. And the plugins media embed work now good. Thanks. :kissing_heart:
